### ISSUE TITLE
Create from template seem to be bugged

### ISSUE THREAD

**Issue by GameFixxer** [tuan3w/obsidian-template#2]
If I try to create a file from any template it is thrown in category uncategorized and is named untitled. The Templates content is applied except from property id and name which is automatically filled with Untitled. Giving it the correct input manually (for example using mostly note template giving the date time for it and the date (year month) for the name does not change the behavior. 

Any idea what I might have done wrong? I just cloned it and started the project so I did not alter anything.
<img width="1025" alt="Bildschirmfoto 2023-11-26 um 11 58 14" src="https://github.com/tuan3w/obsidian-template/assets/63039301/5b0cde7d-dad0-49b7-a5bd-f1c186ae48f3">
<img width="1025" alt="Bildschirmfoto 2023-11-26 um 11 59 42" src="https://github.com/tuan3w/obsidian-template/assets/63039301/b469cbaa-46a9-4252-8b5e-91f119b89471">

Thank you in advance :)

**Comment by tuan3w** [comment]
Hi @GameFixxer,

This template use [Templater](https://github.com/SilentVoid13/Templater) to manage templates. The `id` of the note will be extracted from your note's title. For example, if the title is `123 - Your title` , the id of the note will be `123`. In order to create new note with unique ID, you can use this command to create new note instead. In my Mac, the shortcut key to create new note with unique ID is `cmd + N`.
<img width="730" alt="image" src="https://github.com/tuan3w/obsidian-template/assets/2762678/ef9ce885-4b28-4de1-86f7-985bf5aef460">
